root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  cmd = "go build -o ./tmp/server ./cmd/server/"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "migrations", "testdata"]
  exclude_regex = ["_test\\.go"]
  exclude_file = []
  include_ext = ["go", "yaml", "yml"]
  include_file = []
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
