-- +goose Down

DROP TABLE IF EXISTS creative_sessions CASCADE;
DROP TABLE IF EXISTS viral_videos CASCADE;
DROP TABLE IF EXISTS trend_topics CASCADE;
DROP TABLE IF EXISTS style_presets CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS storyboard_shots CASCADE;
DROP TABLE IF EXISTS storyboards CASCADE;
DROP TABLE IF EXISTS scripts CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS memberships CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
